=== In-somnia/JF4/xml/src/main/resources/books.xsd
<?xml version="1.1" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.my-library.com/books"
        xmlns:tns="http://www.my-library.com/books"
        elementFormDefault="qualified">
    <element name="bookcase" type="tns:bookcase">
        <unique name="id">
            <selector xpath="./bookShelf"/>
            <field xpath="@id"/>
        </unique>
    </element>
    <complexType name="bookcase">
        <sequence>
            <element name="bookShelf" type="tns:bookShelf" maxOccurs="5"/>
        </sequence>
    </complexType>
    <complexType name="bookShelf">
        <sequence>
            <element name="book" type="tns:book" maxOccurs="25"/>
        </sequence>
        <attribute name="id" type="unsignedInt" use="required"/>
    </complexType>
    <complexType name="book">
        <sequence>
            <element name="title" type="normalizedString"/>
            <element name="author" type="string"/>
            <element name="country" type="tns:country"/>
            <element name="year" type="gYear"/>
        </sequence>
    </complexType>
    <simpleType name="country">
        <restriction base="string">
            <enumeration value="Poland"/>
            <enumeration value="UK"/>
            <enumeration value="US"/>
            <enumeration value="Austria"/>
            <enumeration value="Brazil"/>
        </restriction>
    </simpleType>
</schema>

=== In-somnia/JF4/xml/src/main/resources/library.xml
<?xml version="1.1" encoding="UTF-8"?>
    <bookcase xmlns="http://www.my-library.com/bookcase"
        xmlns:book-info="http://www.my-library.com/books"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.my-library.com/books books.xsd">
        <bookShelf id="1">
            <book-info:book>
                <title>Good Omens</title>
                <author>Terry Pratchett, Neil Gaiman</author>
                <country>UK</country>
                <year>2011</year>
            </book-info:book>
            <book-info:book>
                <title>The Witcher</title>
                <author>Andrzej Sapkowski</author>
                <country>Poland</country>
                <year>1986</year>
            </book-info:book>
            <book-info:book>
                <title>The Teachings of Don Juan</title>
                <author>Carlos Castaneda</author>
                <country>US</country>
                <year>1968</year>
            </book-info:book>
            <book-info:book>
                <title>The Lord of The Rings</title>
                <author>J. R. R. Tolkien</author>
                <country>UK</country>
                <year>1954</year>
            </book-info:book>
            <book-info:book>
                <title>Pygmalion</title>
                <author>Bernard Shaw</author>
                <country>Austria</country>
                <year>1912</year>
            </book-info:book>
        </bookShelf>
        <bookShelf id="2">
            <book-info:book>
                <title>Veronika Decides to Die</title>
                <author>Paulo Coelho</author>
                <country>Brazil</country>
                <year>1998</year>
            </book-info:book>
            <book-info:book>
                <title>Harry Potter and The Sorcerer's Stone</title>
                <author>J. K. Rowling</author>
                <country>UK</country>
                <year>1997</year>
            </book-info:book>
        </bookShelf>
    </bookcase>
